### ISSUE TITLE
Server setup

### ISSUE THREAD

**Issue by kngrektor** [AndyBroski/Insplus#3]
Hey im trying to setup a Ins+ server. Right now im just trying on a local cleanly installed server.

Anyways i finally got it to load ( Placed it in a folder and added the folder to gameinfo ) and changed the playlist to "insplus/insplus_pvp". Unfortunatley i get a error when i join the server:
Server is enforcing file consistency for scripts/theaters/insplus_default_firefight.theater

Next join it loads 99% of the file and freezes there until i clear the donwloads directory.
So uuh you have any idea how to fix this?

**Comment by kngrektor** [comment]
I got it working by using workshop version

**Comment by AnSeph** [comment]
The version hosted on github is mainly for version control and safeguarding. Workshop version (although outdated as fuck) would work but it's not fully fledged as the version on here (which will be soon uploaded to the workshop).
